name: Run all Round1 assignments

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run-python-scripts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Run Round1 ques1.py
      run: python Round1/ques1.py

    - name: Run Round1 ques2.py
      run: python Round1/ques2.py

    - name: Run Round1 ques3.py
      run: python Round1/ques3.py
      
    - name: Run Round2 ques1.py
      run: python Round2/ques1.py
      
